### PR TITLE
use OrderedDict and support freeform arrays

### PR DESCRIPTION
**Pull request by tschaume**
This pull request enables two new features:

1. It uses `OrderedDicts` instead of the standard python dictionaries to preserve the structure of the ArchieML file as does [newsdev/archieml-js](https://github.com/newsdev/archieml-js). IMO, this helps spotting parser errors and is in line with ArchieML's goal to make it easy on the user.

2. It implements a first version for the support of freeform arrays tested with [this ArchieML file](https://github.com/materialsproject/MPContribs/blob/f171f4c/test_files/atn_Ni20Fe80Pt10_archieml.txt).

I'd be happy to reiterate and/or discuss the above.

### CODE REVIEW

**Comment by brainkim** [comment]
Hey! Thanks for the effort! Here are my thoughts:
### OrderedDict over Dict
I do think this is preferable and we should probably default to OrderedDicts, but I don't want to lose the ability to generate regular Python Dicts either. Could we figure out a way to pass a Dictionary class into the load/loads functions and the initialization of the loader, similar to [the way `json`](http://stackoverflow.com/questions/6921699/can-i-get-json-to-load-into-an-ordereddict-in-python) does it?

### .swp in .gitignore
I like to avoid having user specific stuff in .gitignores. You can create a global .gitignore to ignore all swp files like so:
`git config --global core.excludesfile '~/.gitignore'`
where `~/.gitignore` is a file in your home directory with all your personal stuff to ignore.

### freeform arrays
Unfortunately, your freeform changes don't see to pass the specification tests. Run these commands in the repository directory to see:
```
git submodule --init --recursive
python setup.py test
```
The tests are pulled from [the archieml.org repository](https://github.com/newsdev/archieml.org/). I don't think I've really wrapped my head around what freeform arrays are but you should check out those test files to see what's up. Also it doesn't seem like freeform stuff has been added to the spec so it'd probably be better to wait for that, but the archieml spec doesn't seem to be very active these days.

Thanks anyways!

**Comment by tschaume** [comment]
Hey Brian,

thanks for the feedback and sorry for not getting back to you earlier.

I reverted the `.gitignore` commit and pulled in the tests. For future readers, the correct command is
```
git submodule update --init --recursive
```
:-) In my case, all 150 tests seem to succeed. Which tests don't pass for you?

Passing a dictionary class is a good idea but probably something I'd have to look into at a later point. We could outsource this into a separate issue or do you consider this a showstopper for merging the pull request?

best, Patrick

**Comment by brainkim** [comment]
Oof not only did I get the submodule command wrong, I also didn't tell you how to change the tests to get them to fail:
https://github.com/brainkim/archieml-python/commit/bad0808ec01e931cd33b3bf0295030c05c296992
If you rebase your current branch off this branch, you'll see that your freeform array stuff doesn't work in weird cases; still haven't looked at which.

Proposal:
If it's possible, let's make this pull request about OrderedDict stuff exclusively, because that does sound really useful, and if you want to deal with the freeform stuff or whatever, you can work off the freeform branch? Might need a little bit of git-fu, and I'd be happy to assist if you don't know how to modify pull requests in place.

Thanks again, and do lemme know if I can be of any help,
Brian

**Comment by tschaume** [comment]
This pull request has been closed and separated into new pull requests #3 and #4.

**Pull request closed without merging**
