### PR TITLE
support for freeform arrays

### PR DESCRIPTION
**Pull request by tschaume**
New pull request separated from #3 (closed). The current solution needs work to make all tests succeed.

### CODE REVIEW

**Comment by tschaume** [comment]
@brainkim, please check out the latest version which passes all tests including the ones for freeform's.

**Comment by brainkim** [comment]
=0 So amazing! I've been really busy but I'll try to look at it by Monday afternoon. Also I need to push to pip but that process is so crufty and annoying that I never get around to doing it. Thanks!

**Comment by tschaume** [comment]
cool, thanks! As for the pip release, you might like @michaeljoseph's [changes](https://github.com/michaeljoseph/changes) package :-) [Here](
http://pythonhosted.org/mpcontribs/develop.html)'s how I use it.

**Comment by brainkim** [comment]
This looks great!
Some thoughts about the code:

1. Can we do it without the not_whitespace regex? Considerations are:
  - I hate python regex’s because I always forget the difference between `match` and `search` 😩.
  - I have to do a tiny bit of mental gymnastics to think about something NOT matching a NOT whitespace pattern in a conditional statement.
  - The other regexs seem more like tokens.

I'd be fine merging this in anyways I'm just trying to be thoughtful about the code. I think that the code would be more coherent if we distinguished regexes that we use b/c they're tokens in the archieml spec vs tokens we use b/c they check or deal with whitespace. I dunno. One quick thing you could do would be to just copy and paste the whitespace pattern into each instance where you use it. I can also just do it myself if that's preferable.

2. Should we put this feature behind a flag? Considerations are:
  - we don't know who's used this package and there might be people who rely on the data being outputted the same way.

Although, it seems like freeform arrays are really useful and it'd be nice to have this feature by default.

Checklist of things to do in chronological order:
- [ ] deploy OrderedDict version (me)
- [ ] discuss the issues above (us)
- [ ] rebase against master (you) (`git rebase brainkim/master`) where `brainkim` is the local copy of `brainkim/master`.
- [ ] add you to contributors in git (me)

Thanks as always!
Brian

**Comment by tschaume** [comment]
I'm not entirely sure why I implemented the `NOT_WS_PATTERN` in the first place but it doesn't seem necessary for the tests to succeed. I removed it and replaced it with `text.strip()` in the one occasion where it's necessary. I agree it's cleaner to stick with `PATTERN` definitions for the actual tokens only.

I don't think a flag is necessary or even wanted since the standard ArchieML specs list freeform arrays as  being supported. So the python parser should support freeform arrays as early as possible, too. They were a major selling point why I decided to use ArchieML. People who relied on freeform arrays being ignored in the python parser should either update their files to comply with the ArchieML specs or use version `0.2.0`.

The `freeform` branch is now rebased against the latest `upstream/master` which includes the use of `OrderedDicts`. Feel free to remove `upstream/freeform`.

I'd be happy to address any other feedback. Best, Patrick

**Comment by brainkim** [comment]
Agreed on all points! Just wanted those decisions to be explicit. I'll make sure to merge and deploy this stuff soon. Also let me know if you want contributor access, so I can add you.

**Comment by tschaume** [comment]
Cool, thanks! Yeah, contributor access would be great. Especially for quick
fixes. I'll still stick to pull requests (maybe from local branches) for
the big changes.

**Comment by brainkim** [comment]
merged directly into master :+1:

**Pull request closed without merging**
